name: Tests

on:
  push:
    branches:
      - master
  pull_request:


jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python3 -m pip install tox
      - run: tox -e lint

  py:
    name: Py
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6,  3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: python3 -m pip install tox
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py -- --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          fail_ci_if_error: true
